### ISSUE TITLE
Loading Kubernetes config into Liberty

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#11350]
The primary use case for feature https://github.com/OpenLiberty/open-liberty/issues/9786 is to allow K8 config (secrets in particular) to be injected into applications.

A couple of suggestions from @arthurdm ;

To match the secret-mounting-behaviour from k8s, a proposal is to define a folder within OL (perhaps configurable), such that each filename in that folder maps to a MP Config `key` and the contents of that file map to that key's `value`.

For example, if we have a secret called `couchDBSecret` with the following items:
```
couchdb.username: arthur
couchdb.password: xzy123
```

Then during deployment the user has two options:
1. Mounting the entire secret to a folder.  
This is done via:
```yaml
...
    volumeMounts:
    - name: couchDB
      mountPath: "/etc/couchdb"
      readOnly: true
  volumes:
  - name: couchDB
    secret:
      secretName: couchDBSecret
...
```
Then inside our container we will have a file with path `/etc/couchdb/couchdb.username`, with value `arthur`, and another file with path `/etc/couchdb/couchdb.password`, with value `xyz123`.

In this scenario our Java app would have:
```java
   @Inject @ConfigProperty(name="couchdb.username") Optional<String> dbUsername;
   @Inject @ConfigProperty(name="couchdb.password") Optional<String> dbPassword;
```

2.  The user can pick which filename and option they use
For example, let's say only the password is needed, you could do:
```yaml
...
    volumeMounts:
    - name: couchDB
      mountPath: "/etc/couchdb"
      readOnly: true
  volumes:
  - name: couchDB
    secret:
      secretName: couchDBSecret
      items:
      - key: password
        path: myPassword
...
```
In this case the only file created is at `/etc/couchdb/myPassword`, with its value being `xyz123`.

In this scenario our Java app would have:
```java
   @Inject @ConfigProperty(name="myPassword") Optional<String> dbPassword;
```

From @Emily-Jiang :
If in Open Liberty, I suggest to create a system property with the default locations separated with comma for the mounting point:

- `liberty.property.mount.dir=/platform/secret/,/platform/bindings/secret`
Where the default value can be overriden.

- Liberty then automatically load these files as variable values and taking the file name as the variable name.

`<variable name="blah" value="hello"/>`
Is the above approach feasible in our liberty config?
