### ISSUE TITLE
Openapi definition of the ChronoUnit enum shows lowercase literals

### ISSUE THREAD

**Issue by srnjak** [OpenLiberty/open-liberty#12679]
In jax-rs representation object I used property of type java.time.temporal.ChronoUnit, which is an enum.

Example:
```
public class MyRepresentation {
    private ChronoUnit chrono;
}
```
In generated openapi document I get literals in lower case:
```
MyRepresentation:
      type: object
      properties:
        chrono:
          type: string
          enum:
          - Nanos
          - Micros
          - Millis
          - Seconds
          - Minutes
          - Hours
          - HalfDays
          - Days
          - Weeks
          - Months
          - Years
          - Decades
          - Centuries
          - Millennia
          - Eras
          - Forever
```
I would expect openapi to be with upper-case literals like this:
```
MyRepresentation:
      type: object
      properties:
        chrono:
          type: string
          enum:
          - NANOS
          - MICROS
          - MILLIS
          - SECONDS
          - MINUTES
          - HOURS
          - HALF_DAYS
          - DAYS
          - WEEKS
          - MONTHS
          - YEARS
          - DECADES
          - CENTURIES
          - MILLENIA
          - ERAS
          - FOREVER
```

 - OpenLiberty Version: 20.0.0.6
 - Java Version: openjdk version "11.0.7" 2020-04-14
