### ISSUE TITLE
MicroProfile OpenAPI: name attribute in @Schema not honored in required properties section

### ISSUE THREAD

**Issue by wahajenius** [OpenLiberty/open-liberty#12947]
**Describe the bug**
When documenting data types with the `@Schema` annotation, it is possible to specify a custom name instead of the default (which is based on the getter name). If the annotation also sets `required = true`, this custom name is correctly used in the `properties` section but not in the `required` section of the generated documentation.

**Steps to Reproduce**
Example class:

```
import org.eclipse.microprofile.openapi.annotations.media.Schema;

@Schema
public final class Foo {
  private String field;

  @Schema(required = true, name = "other")
  public String getBar() {
    return field;
  }
}
```

This results in the following documentation:

```
Foo:
  required:
  - bar
  type: object
  properties:
    other:
      type: string
```

Note that the property is called "bar" in the `required` section and "other" in the `properties` section.

**Expected behavior**

The same custom name should consistently be used in both the `required` and `properties` section:

```
Foo:
  required:
  - other
  type: object
  properties:
    other:
      type: string
```

**Diagnostic information:**
 - OpenLiberty Version: 20.0.0.7
 - server feature microProfile-3.2

**Additional context**
N/A

**Comment by msmiths** [comment]
@arturdzm @leochr @arthurdm

**Comment by Emily-Jiang** [comment]
@wahajenius thanks for reporting this! This issue was fixed in MP OpenAPI 2.0. Will you be able upgrade your application to use the latest feature and it is availabile from 21.0.0.3 and onwards.
```
<featureManager>
    <feature>mpOpenAPI-2.0</feature>
</featureManager>

```

**Comment by wahajenius** [comment]
Thank you for the update. I have retested with 21.0.0.5 and mpOpenAPI-2.0 (via microProfile-4.0). The example case now produces:
```
Foo:
  required:
  - other
  type: object
  properties:
	field:
	  type: string
	other:
	  type: string
```
This does indeed show the preferred name `other` as expected. However, both the getter `other` and its private backing field `field` are now exposed, but the backing field is not annotated with `@Schema`. I would therefore expect the backing field _not_ to be exposed. In fact, it seems that `@Schema` is ignored altogether, because even
```
public final class Foo {
  private String field;
}
```
still results in output
```
Foo:
  type: object
  properties:
	field:
	  type: string
```
Is this by design? If so, how can unwanted class members be hidden from the output?
