### ISSUE TITLE
MicroProfile OpenAPI: @Schema on non-public members is ignored

### ISSUE THREAD

**Issue by wahajenius** [OpenLiberty/open-liberty#13203]
**Describe the bug**
The [schema specification](https://download.eclipse.org/microprofile/microprofile-open-api-1.0/microprofile-openapi-spec.html#_schema) shows that the `@Schema` annotation can be applied to fields. However, the current implementation only yields the correct output when the annotation is applied to _public_ fields or methods.

**Steps to Reproduce**
This is example "Sample 1 - Schema POJO" from [the schema specification](https://download.eclipse.org/microprofile/microprofile-open-api-1.0/microprofile-openapi-spec.html#_schema):
```
@Schema(name="MyBooking", description="POJO that represents a booking.")
public class Booking {
    @Schema(required = true, example = "32126319")
    private String airMiles;

    @Schema(required = true, example = "window")
    private String seatPreference;
}
````

This results in the following YAML:
```
components:
  schemas:
    MyBooking:
      type: object
      description: POJO that represents a booking.
```

Note that there is no `required` and `properties` section. Changing the visibility from `private` to `protected` or default has no effect. However, when they are `public`, or with public getters like this:
```
@Schema(name="MyBooking", description="POJO that represents a booking.")
public class Booking {
  @Schema(required = true, example = "32126319")
  private String airMiles;

  @Schema(required = true, example = "window")
  private String seatPreference;

  public String getAirMiles() {
    return airMiles;
  }

  public String getSeatPreference() {
    return seatPreference;
  }
}
```

Then the output is as expected:
```
components:
  schemas:
    MyBooking:
      required:
      - airMiles
      - seatPreference
      type: object
      properties:
        airMiles:
          type: string
          example: 32126319
        seatPreference:
          type: string
          example: window
      description: POJO that represents a booking.
```

**Expected behavior**
The expected output is shown under the example class:
```
components:
  schemas:
    MyBooking:
      description: POJO that represents a booking.
      required:
      - airMiles
      - seatPreference
      type: object
      properties:
        airMiles:
          type: string
          example: "32126319"
        seatPreference:
          type: string
          example: window
```

**Diagnostic information:**
OpenLiberty Version: 20.0.0.7
server feature microProfile-3.2
