### ISSUE TITLE
RTC250840: SVT: @ApplicationPath("/weather") doesn't show in paths in api documentation

### ISSUE THREAD

**Issue by tam512** [OpenLiberty/open-liberty#1733]
- Using Open Liberty build https://rtpgsa.ibm.com/projects/l/liberty.build/liberty/WASX.LIBERTY/daily/20180110-1030.37.linux/linux/zipper/externals/installables/openliberty-all-17.0.0.4-20180110-1117.zip 
- Test /openapi to see the api document, and I see that the paths doesn't show  /weather in the paths even though I have @javax.ws.rs.ApplicationPath("/weather") in the app.
- Here is a snippet of my WeatherApplication class
```
@javax.ws.rs.ApplicationPath("/weather")
@OpenAPIDefinition(
	..............
		info = @Info(
				title="Weather application",
				description="Weather REST API", 
				termsOfService = "http://example.com/terms/",
				contact = @Contact(
						name = "svt", 
						url = "https://github.com/eclipse/microprofile-open-api",  
						email = "svt@svt-server.com"),
				license = @License(
						name = "Apache 2.0", 
						url = "http://www.apache.org/licenses/LICENSE-2.0.html"),
			    version = "1.0"
			    )
		)
................
................
and
..................
..................
@javax.ws.rs.GET
	@Path("v2/{location}")
```
- Here is a snippet of the api document
```
paths:
  /v2/{location}:
    get:
      tags:
      - Weather API
      summary: Get Weather info v2 at specified location
      operationId: getWeatherv2
```
