### ISSUE TITLE
Complete support for Schema annotation

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/open-liberty#1821]
Complete support for the Schema annotation from the MP OpenAPI spec. Also handle scenarios involving annotations precedence/overrides.

TCK should have some tests to for this annotation. But I recall we removed some tests last minute since we weren't entirely sure what the expected result should be. Ensure those scenarios are covered. (Paul worked on those tests - he may have it saved somewhere).

- [ ]  Schema

**Comment by arturdzm** [comment]
This is schema resulting from Map<String, Stock> inside Portfolio model
We should try create a ref to Stock instead
```
components:
  schemas:
    Portfolio:
      type: object
      properties:
        owner:
          type: string
        total:
          type: number
          format: double
        loyalty:
          type: string
        stocks:
          type: object
          additionalProperties:
            type: object
            properties:
              symbol:
                type: string
              shares:
                type: integer
              date:
                type: string
              price:
                type: number
                format: double
              total:
                type: number
                format: double
```
