### ISSUE TITLE
Reference is not serialized correctly

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/open-liberty#1929]
Reference when serialized uses 'ref'. But it should be '$ref' as per the spec (https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#referenceObject)

Sample output: 
```
      summary: TEST SUMMARY
      operationId: getTestFlights
      parameters:
      - ref: '#/components/parameters/departureDate'
```

It should be 
`      - $ref: '#/components/parameters/departureDate'`

This issue probably affects all referenceable items (not just parameters) except for Schema (which is serialized correctly). Probably due to Schema having it's own serializer. 

This was observed with the output produced by the the model reader app from the TCK (org.eclipse.microprofile.openapi.reader.MyOASModelReaderImpl).
