### ISSUE TITLE
The openapi-3.1 Liberty feature generates wrong property name for annotation @Schema

### ISSUE THREAD

**Issue by andrewnet** [OpenLiberty/open-liberty#21441]
We are using the `openapi-3.1` feature in liberty to generate the Open API documents and found that the @Schema annotation doesn't work as expected. If I annotate a field like the below in my model class
```java
    @Schema(name="asset_id", readOnly = true, required = true)
    private String assetId;
```
The generated swagger doc .yaml file will contain the following
```yaml
RelatedAsset:
  required:
  - assetId         <<----- name of the property in the "required" section is not correct
  - ...
  type: object
  properties:
    asset_id:       <<----- name of the property in the "properties" section is correct
      type: string
      readOnly: true
    ...
```
As you can see the name of the property is generated correctly in the properties section however it is not generated correctly in the required section. The expected name should be the name used in the @Schema annotation, i.e., `asset_id`.

**Diagnostic information:**  
 - OpenLiberty Version: 22.0.0.4
 - Affected feature(s): openapi-3.1
 - Java Version:
```console
sh-4.4$ java -version
Picked up JAVA_TOOL_OPTIONS: -XX:+IgnoreUnrecognizedVMOptions -XX:+UseContainerSupport -XX:+IdleTuningCompactOnIdle -XX:+IdleTuningGcOnIdle
openjdk version "11.0.15" 2022-04-19
OpenJDK Runtime Environment Temurin-11.0.15+10 (build 11.0.15+10)
OpenJDK 64-Bit Server VM Temurin-11.0.15+10 (build 11.0.15+10, mixed mode)
```
 - server.xml configuration
```xml
<featureManager>
    <feature>jaxrs-2.0</feature>
    <feature>ssl-1.0</feature>
    <feature>openapi-3.1</feature>
    <feature>concurrent-1.0</feature>
    <feature>monitor-1.0</feature>
    <feature>localConnector-1.0</feature>
</featureManager>
```

CC @Azquelt
