### ISSUE TITLE
InstantOn with AWS

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#23515]
There are two services we are targeting:
* [Amazon EKS](https://aws.amazon.com/eks/)
* [Amazon ECS](https://aws.amazon.com/ecs/)

**Comment by jgawor** [comment]
# EKS


## EC2: Amazon Linux 2 AMI

Provision EKS v1.24 cluster with the default AMI ( `amiFamily: AmazonLinux2`) nodes: 
```
$ kubectl get node -o wide
NAME                             STATUS   ROLES    AGE    VERSION               INTERNAL-IP      EXTERNAL-IP    OS-IMAGE         KERNEL-VERSION                 CONTAINER-RUNTIME
ip-xx-xxx-xx-xx.ec2.internal     Ready    <none>   107s   v1.24.7-eks-fb459a0   192.168.21.1     x.xxx.xxx.xx   Amazon Linux 2   5.4.226-129.415.amzn2.x86_64   containerd://1.6.6
```

**Status**: InstantOn does not work. Kernel level is not 5.9 or greater. Upgrade to 5.10 is tracked in https://github.com/awslabs/amazon-eks-ami/pull/1118.

## EC2: Ubuntu AMI

Provision EKS v1.24 cluster with `amiFamily: Ubuntu2004` nodes:

```
$ kubectl get node -o wide
NAME                            STATUS   ROLES    AGE     VERSION   INTERNAL-IP     EXTERNAL-IP    OS-IMAGE             KERNEL-VERSION    CONTAINER-RUNTIME
ip-<snip>.ec2.internal          Ready    <none>   6m14s   v1.24.7   192.168.40.75   <snip>         Ubuntu 20.04.5 LTS   5.15.0-1026-aws   containerd://1.5.9
```

**Status**: InstantOn works!

## EC2: Bottlerocket AMI

Provision EKS v1.24 cluster with `amiFamily: Bottlerocket` nodes:

```
$ kubectl get node -o wide
NAME                           STATUS   ROLES    AGE     VERSION               INTERNAL-IP    EXTERNAL-IP     OS-IMAGE                                KERNEL-VERSION   CONTAINER-RUNTIME
ip-xxx-xxx-x-xx.ec2.internal   Ready    <none>   2m19s   v1.24.6-eks-4360b32   192.168.1.77   x.xxx.xxx.xx    Bottlerocket OS 1.11.1 (aws-k8s-1.24)   5.15.59          containerd://1.6.8+bottlerocket
```

**Status**: InstantOn works!

## Fargate profile

Pod does not start. The following error is visible:
```
Warning  FailedScheduling  7s    fargate-scheduler  Pod not supported on Fargate: invalid SecurityContext fields: Capabilities added: NET_ADMIN, SYS_PTRACE, CHECKPOINT_RESTORE
```

**Status**: InstantOn does not work. The Fargate profile does not support enabling the Linux capabilities needed.

**Comment by jgawor** [comment]
## ECS

Task registration fails with the following error:
```
$ aws ecs --region us-east-1 register-task-definition --cli-input-json file://instanton.json 

An error occurred (ClientException) when calling the RegisterTaskDefinition operation: Unrecognized Linux capabilities in add: [CHECKPOINT_RESTORE]
```

### EC2 launch type

**Status**: InstantOn does not work as task registration does not recognize the `CHECKPOINT_RESTORE` capability.  Once that's fixed, InstantOn *should* work with EC2 launch type with Bottlerocket. I opened a case with AWS on the task registration issue.

### Fargate launch type

**Status**: Fargate appears to only support the `SYS_PTRACE` capability.

**Comment by jgawor** [comment]
Sample configuration file for creating EKS cluster using [eksctl](https://eksctl.io/) used in this testing:
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: bottlerocket
  region: us-east-1
  version: '1.24'

managedNodeGroups:
  - name: ng-bottlerocket
    instanceType: t3.micro
    desiredCapacity: 2
    amiFamily: Bottlerocket
    iam:
       attachPolicyARNs:
          - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
          - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
          - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
          - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
```

Same task definition for ECS used in this testing:
```
{
  "containerDefinitions": [
    {
      "name": "liberty",
      "image": "docker.io/jgawor/getting-started-instanton",
      "cpu": 128,
      "memory": 256,
      "essential": true,
      "environment": [
        {
          "name": "CRIU_LOG_LEVEL",
          "value": "4"
        },
        {
          "name": "CRIU_EXTRA_ARGS",
          "value": "--skip-file-rwx-check"
        }
      ],
      "portMappings": [
        {
          "containerPort": 9080,
          "protocol": "tcp"
        }
      ],
      "logConfiguration": {
        "logDriver": "awslogs",
        "options": {
          "awslogs-group": "instanton",
          "awslogs-region": "us-east-1",
          "awslogs-stream-prefix": "ecs"
        }
      },
      "linuxParameters": {
        "capabilities": {
            "add": ["SYS_PTRACE", "NET_ADMIN", "CHECKPOINT_RESTORE"],
            "drop": ["ALL"]
        }
      }
    }
  ],
  "family": "instanton"
}
```
