### ISSUE TITLE
BETA BLOG - MicroProfile OpenAPI endpoint path configuration

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#26222]
The information you provide here will be included in the Open Liberty beta blog post ([example](https://openliberty.io/blog/2020/08/05/jakarta-grpc-beta-20009.html)), which will be published on [openliberty.io/blog/](https://www.openliberty.io/blog/), and potentially elsewhere, to promote this beta feature/function of Open Liberty. For this post to be included in the beta issue please make sure that this is completed by the end of Friday following the GM (Tuesday). The beta and release blogs are created using automation and rely on you following the template's structure. **DO NOT REMOVE/ALTER THE `<GHA>` TAGS THROUGHOUT THIS TEMPLATE.**

Please provide the following information:
&#8203;<GHA-BLOG-RELATED-FEATURES>
1. Which Liberty feature(s) does your update relate to? 
    
    Human-readable name (eg WebSockets feature): MicroProfile OpenAPI
   
    Short feature name (eg websockets-1.0):  `mpOpenAPI-1.0` up to `mpOpenAPI-3.1`
   
   
    </GHA-BLOG-RELATED-FEATURES>

    <GHA-BLOG-TARGET-PERSONA>
2. Who is the target persona? Who do you expect to use the update? eg application developer, operations.

    Application Deployer
    
    
    </GHA-BLOG-TARGET-PERSONA>
   
    <GHA-BLOG-SUMMARY>
3. Provide a summary of the update, including the following points:

   - MicroProfile OpenAPI generates and serves OpenAPI documentation for JAX-RS applications deployed to the Open Liberty server. The OpenAPI documentation is served from `/openapi` and a user interface for browsing this documentation is served from `/openapi/ui`.
   - With this update, you can configure these paths for these endpoints by adding configuration to your server.xml like this:
     
     ```xml
     <mpOpenAPI docPath="/myOpenAPI/path" uiPath="/myUi/Path" />
     ```

   - This is particularly useful if you want to expose the OpenAPI documentation through a Kubernetes ingress which routes requests to different services based on the path.
   - For example, with this ingress configuration:
     ```yaml
     apiVersion: networking.k8s.io/v1
     kind: Ingress
     metadata:
       name: my-ingress
     spec:
       rules:
       - http:
           paths:
           - path: /appA
             pathType: Prefix
             backend:
               service:
                 name: appA
                 port:
                   number: 9080
     ```
   - You could use this server.xml configuration to ensure that the OpenAPI UI is available at `/appA/openapi/ui`:
     ```xml
     <mpOpenAPI docPath="/appA/openapi" />
     ```
     When not set, `uiPath` defaults to `docPath` with `/ui` appended.

    </GHA-BLOG-SUMMARY>

## What happens next?
- Add the label for the beta you're targeting: `target:YY00X-beta`.
- Make sure this blog post is linked back to the Epic for this feature/function.
- Your paragraph will be included in the beta blog post. It might be edited for style and consistency.
- You will be asked to review a draft before publication.
    - Once you've approved the code review, close this issue. 
- If you would _also_ like to write a standalone blog post about your update (highly recommended), raise an issue on the [Open Liberty blogs repo](https://github.com/OpenLiberty/blogs/issues/new/choose). State in the issue that the blog post relates to a specific release so that we can ensure it is published on an appropriate date (it won't be the same day as the beta blog post).
