### ISSUE TITLE
Need empty proxy properties handling

### ISSUE THREAD

**Issue by halim-lee** [OpenLiberty/open-liberty#31268]
When `http_proxy` and `https_proxy` environment properties are set as empty strings, format error is thrown in featureUtility. The code checks for these properties being null only ([http_proxy](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallKernelMap.java#L1961), [https_proxy](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallKernelMap.java#L1978C30-L1978C38)).

Error on older versions of Liberty:
```
java.util.MissingResourceException: Can't find resource for bundle com.ibm.ws.install.internal.resources.InstallKernel, key ERROR_IMPROPER_httpPROXY_FORMAT
```

Error on newer versions of Liberty:
```
CWWKF1400E: The format of the  http_proxy environment variable is invalid. Ensure that the http_proxy variable is in the http_proxy=http://<proxy-host>:<proxy-port> format.
```

From OCP 4.16, it seems that these properties are set as empty strings. If the images are built through  `BuildConfig` process on OCP versions 4.16 or higher, this error will be thrown. The same configuration will not cause the error for OCP 4.15.

To reproduce the error locally, having below in the Dockerfile will cause the error.
```
ENV http_proxy="" https_proxy=""
```

**Comment by halim-lee** [comment]
OCP 4.15 build pod env:
```
spec:
  initContainers:
    - env:
        - name: HTTP_PROXY
        - name: HTTPS_PROXY
        - name: NO_PROXY
```

OCP 4.16 onward build pod env:
```
spec:
  initContainers:
    - env:
        - name: HTTP_PROXY
        - name: http_proxy
        - name: HTTPS_PROXY
        - name: https_proxy
        - name: NO_PROXY
        - name: no_proxy
```


OCP 4.15 [code](https://github.com/openshift/openshift-controller-manager/blob/release-4.15/pkg/build/controller/build/defaults/defaults.go#L98-L100):

```
		externalEnv = append(externalEnv, corev1.EnvVar{Name: "HTTP_PROXY", Value: b.DefaultProxy.HTTPProxy})
		externalEnv = append(externalEnv, corev1.EnvVar{Name: "HTTPS_PROXY", Value: b.DefaultProxy.HTTPSProxy})
		externalEnv = append(externalEnv, corev1.EnvVar{Name: "NO_PROXY", Value: b.DefaultProxy.NoProxy})
```

OCP 4.16 [code](https://github.com/openshift/openshift-controller-manager/blob/release-4.16/pkg/build/controller/build/defaults/defaults.go#L98-L103):

```
		externalEnv = append(externalEnv, corev1.EnvVar{Name: "HTTP_PROXY", Value: b.DefaultProxy.HTTPProxy})
		externalEnv = append(externalEnv, corev1.EnvVar{Name: "http_proxy", Value: b.DefaultProxy.HTTPProxy})
		externalEnv = append(externalEnv, corev1.EnvVar{Name: "HTTPS_PROXY", Value: b.DefaultProxy.HTTPSProxy})
		externalEnv = append(externalEnv, corev1.EnvVar{Name: "https_proxy", Value: b.DefaultProxy.HTTPSProxy})
		externalEnv = append(externalEnv, corev1.EnvVar{Name: "NO_PROXY", Value: b.DefaultProxy.NoProxy})
		externalEnv = append(externalEnv, corev1.EnvVar{Name: "no_proxy", Value: b.DefaultProxy.NoProxy})
```

Code change: https://github.com/openshift/openshift-controller-manager/commit/4f3cde40d0fdee6a7afabdbf0933ceb1f23e13a0
