### ISSUE TITLE
Use MP Config to inject the properties from volume mount 

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/open-liberty#9786]
We need to inject a property defined in a mounted file.  This is an important scenario in a k8s environment, where credentials from a secret are mounted (volumeMount) into the container, rather than bound to env vars.  Maybe we should opt in some folders where any key/values defined there would be available for injection.

**Comment by arthurdm** [comment]
+1

To match the secret-mounting-behaviour from k8s, a proposal is to define a folder within OL (perhaps configurable), such that each filename in that folder maps to a MP Config `key` and the contents of that file map to that key's `value`.

For example, if we have a secret called `couchDBSecret` with the following items:
```
couchdb.username: arthur
couchdb.password: xzy123
```

Then during deployment the user has two options:
1. Mounting the entire secret to a folder.  
This is done via:
```yaml
...
    volumeMounts:
    - name: couchDB
      mountPath: "/etc/couchdb"
      readOnly: true
  volumes:
  - name: couchDB
    secret:
      secretName: couchDBSecret
...
```
Then inside our container we will have a file with path `/etc/couchdb/couchdb.username`, with value `arthur`, and another file with path `/etc/couchdb/couchdb.password`, with value `xyz123`.

In this scenario our Java app would have:
```java
   @Inject @ConfigProperty(name="couchdb.username") Optional<String> dbUsername;
   @Inject @ConfigProperty(name="couchdb.password") Optional<String> dbPassword;
```

2.  The user can pick which filename and option they use
For example, let's say only the password is needed, you could do:
```yaml
...
    volumeMounts:
    - name: couchDB
      mountPath: "/etc/couchdb"
      readOnly: true
  volumes:
  - name: couchDB
    secret:
      secretName: couchDBSecret
      items:
      - key: username
        path: myPassword
...
```
In this case the only file create is at `/etc/couchdb/myPassword`, with its value being `xyz123`.

In this scenario our Java app would have:
```java
   @Inject @ConfigProperty(name="myPassword") Optional<String> dbPassword;
```
